apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-test-app
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
      - name: flask-test-app
        image: nishantaman36/flask-test-app:latest
        ports:
        - containerPort: 5000
